on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on iOS Simulator
    runs-on: macos-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.1.app

      - name: Print Xcode and Swift version
        run: |
          xcodebuild -version
          swift --version

      - name: Install Pods
        run: pod install

      - name: Test 
        env:
          scheme: 'ValuCards'
          platform: 'iOS Simulator'
          device: 'iPhone 14 Pro'
          os: '16.1'
        run: |
          xcodebuild test -workspace "ValuCards.xcworkspace" -scheme "$scheme" -destination "platform=$platform,name=$device,OS=$os" -allowProvisioningUpdates
