on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on Any iOS Simulator
    runs-on: macos-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
      
      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Build
        env:
          scheme: 'ValuCards'
          platform: 'iOS Simulator'
          device: 'iPhone 14 Pro'
          # os: '16.2' # Commentez ou retirez cette ligne pour utiliser la version par défaut du simulateur
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -project "ValuCards.xcodeproj" -destination "platform=$platform,name=$device"
      
      - name: Test
        env:
          scheme: 'ValuCards'
          platform: 'iOS Simulator'
          device: 'iPhone 14 Pro'
          # os: '16.2' # Commentez ou retirez cette ligne pour utiliser la version par défaut du simulateur
        run: |
          xcodebuild test-without-building -scheme "$scheme" -project "ValuCards.xcodeproj" -destination "platform=$platform,name=$device"
